name: Build and Release Magisk Module

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.1)'
        required: true

  # 推送 tag 自动发布（例如 v1.0.0）
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Clean up old outputs
        run: rm -rf output && mkdir output

      - name: Zip Magisk Module
        run: |
          zip -r output/MiSharePlus-MagiskModule.zip . \
            -x ".git/*" ".github/*" "output/*" "*.md" "*.yml" "*.yaml"

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: MiSharePlus Magisk Module
          tag_name: ${{ github.ref_name }}
          files: output/MiSharePlus-MagiskModule.zip
        env:
          GITHUB_TOKEN: ${{ secrets.MISHARE_GITHUB_TOKEN }}  # 使用你添加的密钥名称
