name: Build and Release Magisk Module

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.1)'
        required: true

  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Clean up old outputs
        run: rm -rf output && mkdir output

      - name: Zip Magisk Module
        run: |
          zip -r output/MiSharePlus-MagiskModule.zip . \
            -x ".git/*" ".github/*" "output/*" "*.md" "*.yml" "*.yaml"

      - name: Get release notes from CHANGELOG
        id: changelog
        run: |
          release_notes=$(head -n 10 CHANGELOG.md) # 获取 CHANGELOG.md 文件的前 10 行
          echo "::set-output name=notes::$release_notes" # 设置输出

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: MiSharePlus Magisk Module
          tag_name: ${{ github.ref_name }}
          files: output/MiSharePlus-MagiskModule.zip
          body: ${{ steps.changelog.outputs.notes }}  # 使用从 CHANGELOG.md 提取的说明
        env:
          GITHUB_TOKEN: ${{ secrets.MISHARE_GITHUB_TOKEN }}
